export enum ROUTES {
  AUTHENTICATION_STACK = 'AUTHENTICATION_STACK',
  REGISTER_DRIVER_STACK = 'REGISTER_DRIVER_STACK',
  MAIN_STACK = 'MAIN_STACK',
  EARNINGS_STACK = 'EARNINGS_STACK',
  ORDERS_STACK = 'ORDERS_STACK',
  BALANCE_STACK = 'BALANCE_STACK',
  SETTINGS_STACK = 'SETTINGS_STACK',
  SUPPORT_STACK = 'SUPPORT_STACK',

  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
  LOGIN = 'LOGIN',
  ENTER_CODE = 'ENTER_CODE',

  NOTIFICATIONS = 'NOTIFICATIONS',
  ORDERS = 'ORDERS',
  PROFILE = 'PROFILE',
  SETTINGS = 'SETTINGS',

  SUPPORT = 'SUPPORT',
  SUPPORT_CATEGORY = 'SUPPORT_CATEGORY',
  CHAT = 'CHAT',
  MAP = 'MAP',
  TRIP = 'TRIP',
  SELECT_CAR = 'SELECT_CAR',
}
