export enum ROUTES {
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
  LOGIN = 'LOGIN',
  ENTER_CODE = 'ENTER_CODE',

  NOTIFICATIONS = 'NOTIFICATIONS',
  ORDERS = 'ORDERS',
  PROFILE = 'PROFILE',
  SETTINGS = 'SETTINGS',

  SUPPORT = 'SUPPORT',
  CHAT = 'CHAT',
  MAP = 'MAP',
  TRIP = 'TRIP',
  SELECT_CAR = 'SELECT_CAR',

  MY_ADDRESSES = 'MY_ADDRESSES',
  ADD_ADDRESS = 'ADD_ADDRESS',
  SELECT_ADDRESS_MAP = 'SELECT_ADDRESS_MAP',
}
