require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'

target 'snapTaxi' do

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  target 'snapTaxiTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'snapTaxi-tvOS' do
  # Pods for snapTaxi-tvOS

  target 'snapTaxi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
