import LocalizedStrings from 'react-native-localization';
import React from 'react';

let strings = new LocalizedStrings({
  ru: {
    goodMorning: 'Доброе утро',
    goodDay: 'Добрый день',
    goodEvening: 'Добрый вечер',
    whereAreWeGoing: 'Куда мы едем ?',
    send: 'Отправить',
    continue: 'Продолжить',
    where: 'Куда едем?',
    map: 'Карта',
    from: 'Едем из',
    to: 'Едем в',
    notifications: 'Уведомление',
    findTaxi: 'Найти такси',
    forFriend: 'Для друга',
    additional: 'Дополнительно',
    fee: 'Цена за поездку',
    cancelTrip: 'Отменить поездку',
    moreTaxi: 'Еще такси',
    cancel: 'Отменить',
    howWasTrip: 'Как вам поездка?',
    helpUsToBeBetter:
      'Помогите нам улучшить наш сервис и ваши ощущения во время поездки',
    yourMark: 'Ваша оценка',
    leaveFeedBack: 'Напишите ваш отзыв',
    tripFinished: 'Поездка завершена',
    tripDistance: 'Расстояние',
    tripTime: 'Время',
    tripCost: 'Сумма',
    addCard: 'Добавить карту',
    save: 'Сохранить',
    cardDate: 'год/месяц',
    phone: 'номер телефона',
    myTrips: 'Мои поездки',
    myAddresses: 'Мои адреса',
    yourDesire: 'Ваши пожелания',
    airCondition: 'Кондиционер',
    forSmokers: 'Авто для курящих',
    comment: 'Комментарий водителю',
    planInfo: 'Информация о тарифе',
    car: 'Автомобиль',
    plan: 'Тариф',
    costPerKm: 'Стоимость 1 км',
    costForWait: 'Ожидание 1 мин',
    understandable: 'Понятно',
    settings: 'Настройки',
    showTrafficJams: 'Пробки на карте',
    appLanguage: 'Язык приложения',
    dontCall: 'Не звонить',
    dontNotifySale: 'Не предлагать сообщения о снижении цен',
    sale: 'Скидки',
    apply: 'Применить',
    byCash: 'Наличность',
    byCard: 'Картой',
    paymentMethods: 'Способ оплаты',
    newCard: 'Новая карта',
    enterPromoCode: 'Ввести промокод',
    addAddress: 'Добавить Адрес',
    done: 'Готово',
    chat: 'Чат с водителем',
    writeSMS: 'Напишите сообщение...',
    changeAddress: 'Изменить адрес',
    next: 'Далее',
    discounts: 'Скидки',
    support: 'Служба поддержки',
    beDriver: 'Стать водителем',
    user: 'Пользователь',
    yourName: 'Ваше имя',
    noTrips: 'Нет поездок',
    rateTitle: 'Тариф',
    accepted: 'Машина подан',
    onWay: 'В пути',
    carWaiting: 'Машина ожидает',
    carArrived: 'Машина прибыла',
  },
  en: {
    goodMorning: 'Good morning',
    goodDay: 'Good day',
    goodEvening: 'Good evening',
    whereAreWeGoing: 'Where to go?',
    send: 'Send',
    continue: 'Continue',
    where: 'Where we go?',
    map: 'Map',
    from: 'We go from',
    to: 'We go to',
    findTaxi: 'Find taxi',
    forFriend: 'Для друга',
    additional: 'Additional',
    fee: 'Fee',
    cancelTrip: 'Cancel trip',
    moreTaxi: 'Еще такси',
    cancel: 'Cancel',
    howWasTrip: 'How do you ride?',
    helpUsToBeBetter: 'Help us improve our service and your travel experience',
    yourMark: 'Your mark',
    leaveFeedBack: 'Write your review',
    tripFinished: 'Trip completed',
    tripDistance: 'Distance',
    tripTime: 'Time',
    tripCost: 'Amount',
    addCard: 'Add card',
    save: 'Save',
    cardDate: 'year/month',
    phone: 'phone number',
    myTrips: 'My trips',
    myAddresses: 'My addresses',
    yourDesire: 'Your wishes',
    airCondition: 'Air conditioning',
    forSmokers: 'Авто для курящих',
    comment: 'Driver comment',
    planInfo: 'Tariff information',
    car: 'Car',
    plan: 'Tariff',
    costPerKm: 'Cost of 1 km',
    costForWait: 'Waiting 1 min',
    understandable: 'Understandable',
    settings: 'Settings',
    showTrafficJams: 'Show traffic-jams on map',
    appLanguage: 'App language',
    dontCall: 'Do not call',
    dontNotifySale: 'Do not offer price cut messages',
    sale: 'Discounts',
    apply: 'Apply',
    byCash: 'Cash',
    byCard: 'By card',
    paymentMethods: 'Payment method',
    newCard: 'New map',
    enterPromoCode: 'Enter promo code',
    addAddress: 'Add Address',
    done: 'Done',
    chat: 'Chat with driver',
    writeSMS: 'Write a message...',
    changeAddress: 'Change address',
    next: 'Next',
    discounts: 'Discounts',
    support: 'Support',
    beDriver: 'Be Driver',
    user: 'User',
    yourName: 'Your name',
    noTrips: 'No trips',
    notifications: 'Notifications',
    rateTitle: 'Rate',
    accepted: 'Accepted',
    onWay: 'On the way',
    carWaiting: 'Waiting',
    carArrived: 'Arrived',
  },
  uz: {
    goodMorning: 'Xayirli tong',
    goodDay: 'Xayilri kun',
    goodEvening: 'Xayirli kech',
    whereAreWeGoing: 'Qayerga biz boramiz?',
    send: 'Yuborish',
    continue: 'Davom etirish',
    where: 'Qayerga boramiz?',
    map: 'Karta',
    from: 'Qayerdan ketasiz?',
    to: 'Qayerga ketvomiz?',
    notifications: 'Bildirishnoma',
    findTaxi: 'Taksi topish',
    forFriend: 'Dostim uchun',
    additional: 'Qoshimchalar',
    fee: 'Safar narxi',
    cancelTrip: 'Safarni bekor qilish',
    moreTaxi: 'Yana taksi',
    cancel: 'Bekor qilish',
    howWasTrip: 'Safaringiz qanday otdi?',
    helpUsToBeBetter:
      'Xizmatlarimizni yaxshilash maqsadida. Safar davomida oz tasurotlaringizni qoldiring',
    yourMark: 'Sizning bahoingiz',
    leaveFeedBack: 'Oz fikrigizni yozib qoldiring',
    tripFinished: 'Safar yakunlandi',
    tripDistance: 'Masofa',
    tripTime: 'Vaqt',
    tripCost: 'Narxi',
    addCard: 'Kartani qoshish',
    save: 'Saqlash',
    cardDate: 'yil/oy',
    phone: 'Telefon raqamingiz',
    myTrips: 'Mening safarlarim',
    myAddresses: 'Mening manzillarim',
    yourDesire: 'Sizning tilaklaringiz',
    airCondition: 'Кondisioner',
    forSmokers: 'Chekuvchilar uchun avto',
    comment: 'Xaydovchilar uchun izohlar',
    planInfo: 'Tariflar haqida malumot',
    car: 'Аvtomobil',
    plan: 'Тarif',
    costPerKm: 'Narx',
    costForWait: 'Kutish',
    understandable: 'Chunarli',
    settings: 'Sozlash',
    showTrafficJams: 'Kartada tirbandliklar',
    appLanguage: 'Dastur tili',
    dontCall: 'Qongiroq qilmang',
    dontNotifySale: 'Narxlar pasayishi togrisida xabar bermang',
    sale: 'Chegirmalar',
    apply: 'Qollash',
    byCash: 'Naqt pul',
    byCard: 'Karta',
    paymentMethods: 'Tolov turi',
    newCard: 'Yangi karta',
    enterPromoCode: 'Promokodni kiriting',
    addAddress: 'Manzil qoshish',
    done: 'Bajarildi',
    chat: 'Xaydovchi bilan chat',
    writeSMS: 'Xabar yozib yuboring…',
    changeAddress: 'Manzilni ozgartirish',
    next: 'Keyingi',
    discounts: 'СHegirmalar',
    support: 'Qollab – quvattlash xizmati ',
    beDriver: 'Haydovchi bolish',
    user: 'Foydalanuvchi',
    yourName: 'Sizning ismingiz',
    noTrips: 'Safarlaringiz yoq',
    rateTitle: 'Тarif',
    accepted: 'Мoshina jonatildi',
    onWay: 'Yolda',
    carWaiting: 'Мoshina kutmoqda',
    carArrived: 'Мoshina yetib keldi',
  },
});

export { strings as localization };
