import LocalizedStrings from 'react-native-localization';
import React from "react";

let strings = new LocalizedStrings({
    ru: {
        goodMorning: 'Доброе утро',
        whereAreWeGoing: 'Куда мы едем?',
        send: 'Отправить',
        continue: 'Продолжить',
        where: "Куда едем?",
        map: 'Карта',
        from: 'Едем из',
        to: 'Едем в',
        findTaxi: 'Найти такси',
        forFriend: 'Для друга',
        additional: 'Дополнительно',
        fee: 'Цена за поездку',
        cancelTrip: "Отменить поездку",
        moreTaxi: 'Еще такси',
        cancel: 'Отменить',
        howWasTrip: 'Как вам поездка?',
        helpUsToBeBetter: 'Помогите нам улучшить наш сервис и ваши ощущения во время поездки',
        yourMark: 'Ваша оценка',
        leaveFeedBack: 'Напишите ваш отзыв',
        tripFinished: 'Поездка завершена',
        tripDistance: 'Расстояние',
        tripTime: 'Время',
        tripCost: 'Сумма',
        addCard: 'Добавить карту',
        save: 'Сохранить',
        cardDate: 'год/месяц',
        phone: 'номер телефона',
        myTrips: 'Мои поездки',
        myAddresses: 'Мои адреса',
        yourDesire: 'Ваши пожелания',
        airCondition: 'Кондиционер',
        forSmokers: 'Авто для курящих',
        comment: 'Комментарий водителю',
        planInfo: 'Информация о тарифе',
        car: 'Автомобиль',
        plan: 'Тариф',
        costPerKm: 'Стоимость 1 км',
        costForWait: 'Ожидание 1 мин',
        understandable: 'Понятно',
        settings: 'Настройки',
        showTrafficJams: 'Пробки на карте',
        appLanguage: 'Язык приложения',
        dontCall: 'Не звонить',
        dontNotifySale: 'Не предлагать сообщенияо снижении цен',
        clearCashCard: 'Очистить  кэш карт',
        sale: 'Скидки',
        apply: 'Применить',
        byCash: 'Наличность',
        byCard: 'Картой',
        paymentMethods: 'Способ оплаты',
        newCard: 'Новая карта',
        enterPromoCode: 'Ввести промокод',
        addAddress: 'Добавить Адрес',
        done: 'Готово'
    },
    uz: {
        where: "Куда едем?"
    },
    eng: {}
});
export {strings as localization}
