import LocalizedStrings from 'react-native-localization';
import React from "react";

let strings = new LocalizedStrings({
    'ru': {
        goodMorning: 'Доброе утро',
        goodDay: 'Добрый день',
        goodEvening: 'Добрый вечер',
        whereAreWeGoing: 'Куда мы едем?',
        send: 'Отправить',
        continue: 'Продолжить',
        where: "Куда едем?",
        map: 'Карта',
        from: 'Едем из',
        to: 'Едем в',
        findTaxi: 'Найти такси',
        forFriend: 'Для друга',
        additional: 'Дополнительно',
        fee: 'Цена за поездку',
        cancelTrip: "Отменить поездку",
        moreTaxi: 'Еще такси',
        cancel: 'Отменить',
        howWasTrip: 'Как вам поездка?',
        helpUsToBeBetter: 'Помогите нам улучшить наш сервис и ваши ощущения во время поездки',
        yourMark: 'Ваша оценка',
        leaveFeedBack: 'Напишите ваш отзыв',
        tripFinished: 'Поездка завершена',
        tripDistance: 'Расстояние',
        tripTime: 'Время',
        tripCost: 'Сумма',
        addCard: 'Добавить карту',
        save: 'Сохранить',
        cardDate: 'год/месяц',
        phone: 'номер телефона',
        myTrips: 'Мои поездки',
        myAddresses: 'Мои адреса',
        yourDesire: 'Ваши пожелания',
        airCondition: 'Кондиционер',
        forSmokers: 'Авто для курящих',
        comment: 'Комментарий водителю',
        planInfo: 'Информация о тарифе',
        car: 'Автомобиль',
        plan: 'Тариф',
        costPerKm: 'Стоимость 1 км',
        costForWait: 'Ожидание 1 мин',
        understandable: 'Понятно',
        settings: 'Настройки',
        showTrafficJams: 'Пробки на карте',
        appLanguage: 'Язык приложения',
        dontCall: 'Не звонить',
        dontNotifySale: 'Не предлагать сообщения о снижении цен',
        sale: 'Скидки',
        apply: 'Применить',
        byCash: 'Наличность',
        byCard: 'Картой',
        paymentMethods: 'Способ оплаты',
        newCard: 'Новая карта',
        enterPromoCode: 'Ввести промокод',
        addAddress: 'Добавить Адрес',
        done: 'Готово',
        chat: "Чат с водителем",
        writeSMS: 'Напишите сообщение...',
        changeAddress: 'Изменить адрес',
        next: 'Далее',
    },
    'en': {
        goodMorning: 'Good morning',
        goodDay: 'Good day',
        goodEvening: 'Good evening',
        whereAreWeGoing: 'Where to go?',
        send: 'Send',
        continue: 'Continue',
        where: "Where we go?",
        map: 'Map',
        from: 'We go from',
        to: 'We go to',
        findTaxi: 'Find taxi',
        forFriend: 'Для друга',
        additional: 'Additional',
        fee: 'Fee',
        cancelTrip: "Cancel trip",
        moreTaxi: 'Еще такси',
        cancel: 'Cancel',
        howWasTrip: 'How do you ride?',
        helpUsToBeBetter: 'Help us improve our service and your travel experience',
        yourMark: 'Your mark',
        leaveFeedBack: 'Write your review',
        tripFinished: 'Trip completed',
        tripDistance: 'Distance',
        tripTime: 'Time',
        tripCost: 'Amount',
        addCard: 'Add card',
        save: 'Save',
        cardDate: 'year/month',
        phone: 'phone number',
        myTrips: 'My trips',
        myAddresses: 'My addresses',
        yourDesire: 'Your wishes',
        airCondition: 'Air conditioning',
        forSmokers: 'Авто для курящих',
        comment: 'Driver comment',
        planInfo: 'Tariff information',
        car: 'Car',
        plan: 'Tariff',
        costPerKm: 'Cost of 1 km',
        costForWait: 'Waiting 1 min',
        understandable: 'Understandable',
        settings: 'Settings',
        showTrafficJams: 'Show traffic-jams on map',
        appLanguage: 'App language',
        dontCall: 'Do not call',
        dontNotifySale: 'Do not offer price cut messages',
        sale: 'Discounts',
        apply: 'Apply',
        byCash: 'Cash',
        byCard: 'By card',
        paymentMethods: 'Payment method',
        newCard: 'New map',
        enterPromoCode: 'Enter promo code',
        addAddress: 'Add Address',
        done: 'Done',
        chat: "Chat with driver",
        writeSMS: 'Write a message...',
        changeAddress: 'Change address',
        next: 'Next',
    }
});
export {strings as localization}
